name: Spider Runner And Web Build

# 触发条件
on:
  # 每天凌晨 0 点执行，仅在 dev 分支触发
  schedule:
    - cron: '0 0 * * *'
  # 手动触发，仅在 dev 分支触发
  workflow_dispatch:
  # 当 push 到 dev 分支时触发
  push:
    branches:
      - dev
      - main

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 安装依赖
      - name: Install dependencies
        working-directory: spider
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 执行脚本
      - name: Run spider script
        working-directory: spider
        run: python run_spider.py

      # 设置node环境
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 安装依赖、构建网站
      - name: Build website
        working-directory: web
        run: |
          npm install
          npm run build

      # 提交dist目录到gh-pages分支
      - name: Commit website to gh-pages branch
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add -f web/dist
          git commit -m "Commit website" || echo "No changes to commit"
          git subtree push --prefix web/dist origin gh-pages
