name: Spider Runner

# 触发条件
on:
  # 每天凌晨 0 点执行，仅在 dev 分支触发
  schedule:
    - cron: '0 0 * * *'
  # 手动触发，仅在 dev 分支触发
  workflow_dispatch:
  # 当 push 到 dev 分支时触发
  push:
    branches:
      - dev
      - main

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 安装依赖
      - name: Install dependencies
        working-directory: spider
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 执行脚本
      - name: Run spider script
        working-directory: spider
        run: python run_spider.py

      # 提交更改
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "[skip actions] Update data generated by spider"
            git push origin dev
          else
            echo "No changes to commit."
          fi